# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master]

jobs:  
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2  
        
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3        
        with:
          host: ${{ secrets.SSH_HOST }} #IP
          key: ${{ secrets.SSH_KEY }} #PrivateKey
          username: ${{ secrets.SSH_USERNAME }} #username 
          envs: GITHUB_SHA,COMMAND
          script: ls
